### ISSUE TITLE
Possibly Incorrect Values

### ISSUE THREAD

**Issue by kaustubh-karkare** [browning/tiger-hash-python#1]
I was trying to use your library in one of my scripts, and upon testing i believe that the values being generated by this library are incorrect. For instance:

Source: https://github.com/browning/tiger-hash-python

> > > import tiger
> > > tiger.hash("")
> > > '24F0130C63AC933216166E76B1BB925FF373DE2D49584E7A'

Source: http://en.wikipedia.org/wiki/Tiger_%28hash%29
The hash of the zero-length string is:
Tiger("") =
3293ac630c13f0245f92bbb1766e16167a4e58492dde73f3

Is this really a problem, or am I mistaken somewhere?

**Comment by browning** [comment]
Thanks, Its a good point, this library is a copy of the reference implementation which prints out the hash differently than the wikipedia example. So, its basically the same hash, but it looks different. It looks like the wikipedia example is the standard way to do it though so we will want to change this library eventually to support this.

You can convert our way to the wikipedia way by splitting it up like so into 8 byte segments:
24F0130C63AC933216166E76B1BB925FF373DE2D49584E7A
24F0130C63AC9332-------------16166E76B1BB925F-------------F373DE2D49584E7A
Then reversing the bytes in each of those 3 segment and pushing them back together.
Its big endian / little endian related.
